import localFont from "next/font/local";
import "./globals.css";
import HeaderWrapper from "./components/HeadWrapper";

const kanit = localFont({
  src: [
    {
      path: "../fonts/kanit/kanit-v17-latin-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/kanit/kanit-v17-latin-500.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/kanit/kanit-v17-latin-700.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-kanit",
  display: "swap",
});

export const metadata = {
  title: "GoalLine Turf",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${kanit.variable} h-full antialiased`}>
      <body className="min-h-screen flex flex-col w-full items-center">
        <a href="#main-content" className="sr-only focus:not-sr-only ">
          Skip to content
        </a>
        <HeaderWrapper />

        <main
          id="main-content"
          className="w-full flex flex-col flex-1 mt-18 gap-8"
        >
          {children}
        </main>
      </body>
    </html>
  );
}
