import localFont from "next/font/local";
import "./globals.css";
import HeaderWrapper from "./components/HeadWrapper";
import SiteLayout from "./(site)/layout";
import Footer from "./components/Footer";
import { BookingProvider } from "@/context/BookingContext";

const kanit = localFont({
  src: [
    {
      path: "../fonts/kanit/kanit-v17-latin-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/kanit/kanit-v17-latin-500.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/kanit/kanit-v17-latin-700.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-kanit",
  display: "swap",
});

export const metadata = {
  title: "GoalLine Turf",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${kanit.variable} h-full antialiased `}>
      <body className="flex flex-col min-h-screen">
        <BookingProvider>
          <a href="#main-content" className="sr-only focus:not-sr-only "></a>
          <header>
            <HeaderWrapper />
          </header>
          {children}
        </BookingProvider>
      </body>
    </html>
  );
}
